public enum Modulo {
    NULL, PROGRAMACION_DE_DISPOSITIVOS_MOVILES, SISTEMAS_GESTION_EMPRESARIAL, ACCESO_A_DATOS, PROGRAMACION_DE_SERVICIOS_Y_PROCESOS,
    DESARROLLO_DE_INTERFACES, EMPRESA_E_INICIATIVA_EMPRENDEDORA
}
